CORCI-1162 Test: NOT FOR LANDING
daos-stack/pipeline-lib pull request #289
Opened 2022-02-28 19:21 UTC by JohnMalmberg

Test PR to debug/verify repository updating

Signed-off-by: John E Malmberg <john.e.malmberg@intel.com>

2022-03-04 16:15 UTC, daosbuild1 commented
Test stage provisionNodes with slurm Leap15 completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/pipeline-lib/job/PR-289/6/display/redirect

2022-03-04 16:15 UTC, daosbuild1 commented
Test stage provisionNodes with release/2.0 Repo completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/pipeline-lib/job/PR-289/6/display/redirect

2022-03-04 16:15 UTC, daosbuild1 commented
Test stage provisionNodes with slurm EL8 completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/pipeline-lib/job/PR-289/6/display/redirect

2022-03-04 16:15 UTC, daosbuild1 commented
Test stage provisionNodes with master Repo completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/pipeline-lib/job/PR-289/6/display/redirect

2022-03-04 16:46 UTC, brianjmurrell reviewed
Should we add a Ubuntu upload test to this repo now?

2022-03-04 18:07 UTC, jolivier23 requested changes

2022-03-04 18:07 UTC, jolivier23 commented on vars/buildRpmPost.groovy
> +
```suggestion
    String repo_format = 'yum'
    if (!target.startsWith('ubuntu')) {
        stash name: target + '-required-mercury-rpm-version',
              includes: target + '-required-mercury-rpm-version'
    } else { 
        repo_format = 'apt'
    }

```

2022-03-14 15:43 UTC, daosbuild1 commented
Test stage provisionNodes with slurm Leap15 completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/pipeline-lib/job/PR-289/10/display/redirect

2022-03-14 18:52 UTC, brianjmurrell requested changes

2022-03-14 18:52 UTC, brianjmurrell commented on Jenkinsfile
> +        ARTIFACTORY_URL = 'https://artifactory.dc.hpdd.intel.com/'
Just a note to myself to make sure this is removed before final review/landing.

2022-03-14 18:52 UTC, brianjmurrell commented on Jenkinsfile
> +@Library(value="pipeline-lib@corci-1162") _
Just a note to myself to make sure this is removed before final review/landing.

2022-03-14 18:52 UTC, brianjmurrell commented on Jenkinsfile
> +@Library(value="pipeline-lib@corci-1162") _
```suggestion
@Library(value="pipeline-lib@corci-1162a") _
```

2022-03-14 19:48 UTC, daosbuild1 commented
Test stage provisionNodes with slurm Leap15 completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/pipeline-lib/job/PR-289/13/display/redirect

2022-03-14 20:53 UTC, daosbuild1 commented
Test stage provisionNodes with slurm Leap15 completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/pipeline-lib/job/PR-289/16/display/redirect

2022-03-15 00:32 UTC, daosbuild1 commented
Test stage provisionNodes with slurm Leap15 completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/pipeline-lib/job/PR-289/17/display/redirect

2022-03-15 13:56 UTC, daosbuild1 commented
Test stage provisionNodes with slurm Leap15 completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/pipeline-lib/job/PR-289/18/display/redirect

2022-03-15 14:05 UTC, daosbuild1 commented
Test stage provisionNodes with slurm Leap15 completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/pipeline-lib/job/PR-289/19/display/redirect

2022-03-15 15:46 UTC, brianjmurrell reviewed
Generally looks good.  I do think we need to think about the `yum`->`dnf` change in provisionNodesV1 though.  Hoping you can do some analysis about what the fallout of that change could be.  Is it going to end up getting used (i.e. in some historic release) where DNF is not actually available?

2022-03-15 15:46 UTC, brianjmurrell commented on vars/provisionNodesV1.groovy
>                               yum -y erase metabench mdtest simul IOR compat-openmpi16
Why not use `dnf` here also?  Mixing `yum` and `dnf` means duplicate package libraries including duplicate downloads of repo data.

There might be other uses of YUM that we want to switch to DNF.

2022-03-15 16:09 UTC, daosbuild1 commented
Test stage provisionNodes with slurm EL7 completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/pipeline-lib/job/PR-289/22/display/redirect

2022-03-15 17:45 UTC, daosbuild1 commented
Test stage provisionNodes with release/0.9 Repo completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/pipeline-lib/job/PR-289/24/display/redirect

2022-03-15 17:46 UTC, daosbuild1 commented
Test stage provisionNodes with master Repo completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/pipeline-lib/job/PR-289/24/display/redirect

2022-03-15 17:50 UTC, daosbuild1 commented
Test stage provisionNodes with slurm EL7 completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/pipeline-lib/job/PR-289/24/display/redirect

2022-03-15 18:03 UTC, JohnMalmberg commented on vars/provisionNodesV1.groovy
> +                             if ! dnf -y install --exclude=ompi CUnit python36-PyYAML          \
Added making sure DNF is installed, which means that provisionNodesV1 is as backward compatible as currently possible.

2022-03-15 18:05 UTC, brianjmurrell commented on vars/provisionNodesV1.groovy
>                               yum -y erase metabench mdtest simul IOR compat-openmpi16
>  I think we want look at removing the tests using provisionNodesV1 instead of trying to optimize it.

daos-stack/pipeline-lib#287 does that IIRC.

2022-03-15 18:10 UTC, brianjmurrell approved these changes

2022-03-15 18:22 UTC, merged