SRE-97 Build: Add support for el-8 unit tests
daos-stack/pipeline-lib pull request #320
Opened 2022-06-22 21:35 UTC by JohnMalmberg

Add support for el-8 Unit tests.

Signed-off-by: John E Malmberg <john.e.malmberg@intel.com>

2022-06-25 07:44 UTC, ashleypittman commented on vars/sconsBuild.groovy
> +
All the dockerfiles have used 'scons' installed through pip for some months now, no change to support dockerfile building should be considering scons-3 at all.

2022-06-28 18:01 UTC, brianjmurrell approved these changes

2022-06-28 18:03 UTC, ashleypittman requested changes
@brianjmurrell is correct, but I do not believe we need the scons/scons-3 change at all.

2022-07-26 18:18 UTC, JohnMalmberg commented
Current push uses more concise code, which will try the traditional name first and the el-8 distro name second so that if we ever need to make a change to use the distro scons on el-8, we do not have to also modify pipeline-lib.

2022-08-02 16:53 UTC, brianjmurrell approved these changes

2022-08-02 18:11 UTC, merged