DAOS-623 pmdk: mimic how PMDK's CI prepares docker's tmpfs for tests
daos-stack/pipeline-lib pull request #381
Opened 2023-06-21 12:05 UTC by janekmi

Required by daos-stack/pmdk and especially by daos-stack/pmdk#26. Tests fail currently because flock(2) allows locking file which is already locked exclusively.

The introduced tmpfs is intended to closely resemble how tmpfs works without docker involved.

Ref: pmem/pmdk#4467

2023-06-21 12:16 UTC, grom72 approved these changes

2023-06-21 12:27 UTC, brianjmurrell commented
I'm not quite sure I understand how/why having a `tmpfs` on `/tmp` is making a difference.  Do I understand that you are saying that `flock(2)` is not working correctly on the `/tmp` that is in the docker container without a `tmpfs` mounted on it?

2023-06-21 12:32 UTC, brianjmurrell requested changes

2023-06-21 12:32 UTC, brianjmurrell commented on vars/packageBuildingPipeline.groovy
There are two other `packageBuildingPipeline*()` functions that will need this modification.  It is unfortunate that we now have three of them, indeed.  I personally consider this one and `packageBuildingPipelineDAOS()` to be somewhat deprecated since `packageBuildingPipelineDAOSTest()` provides **much** better testing than the other two.  Not all projects that use the `packageBuildingPipeline*()` pipelines have been converted to `packageBuildingPipelineDAOSTest()`  yet and/or nobody has found the time to DRY these 3 different pipelines out into a single pipeline that can take parameters to act like any of the 3 do.

2023-06-21 19:37 UTC, grom72 commented
More detailed explanation can be found here: https://daosio.atlassian.net/browse/PMDK-72

2023-06-21 22:40 UTC, jolivier23 commented on vars/packageBuildingPipeline.groovy
We should switch pmdk to use the newer one if we are not already.

2023-06-22 12:04 UTC, janekmi commented
I am closing this one because the solution on the `docker` level is not sufficient since `mock` is used in this case. For details please see daos-stack/pmdk#31. @brianjmurrell there are also a little bit more details on the `flock(2)` issue if you are interested. Thanks!

2023-06-22 12:04 UTC, closed without merging