SRE-1904 Diagnostic test
daos-stack/pipeline-lib pull request #385
Opened 2023-06-30 15:10 UTC by JohnMalmberg

Diagnostic test for SRE-1904

2023-06-30 16:40 UTC, JohnMalmberg commented
This is needed to help diagnose SRE-1904 which only is showing up on timed or merges to to the release/2.4 branch.

2023-07-05 21:26 UTC, daosbuild1 commented
Test stage provisionNodes with slurm Leap15 completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/pipeline-lib/job/PR-385/3/display/redirect

2023-07-05 21:26 UTC, daosbuild1 commented
Test stage provisionNodes on EL 8 with slurm completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/pipeline-lib/job/PR-385/3/display/redirect

2023-07-06 14:51 UTC, brianjmurrell requested changes
Do you have a Jenkins run with the fix removed to show that the tests catch the issue?

2023-07-06 14:51 UTC, brianjmurrell commented on Jenkinsfile
> +                        withEnv(['BRANCH_NAME=release2.4']) {
The branch name is `release/2.4`.

```suggestion
                        withEnv(['BRANCH_NAME=release/2.4']) {
```

It probably doesn't make a material difference to the test, but should be accurate at least for appearances sake.

2023-07-06 14:51 UTC, brianjmurrell commented on Jenkinsfile
Might add a Leap 15.4 test there to exercise the RE a bit more.

2023-07-06 15:23 UTC, JohnMalmberg commented
Will remove the Jenkinsfile pipeline-lib self reference on the next push.

2023-07-06 16:31 UTC, brianjmurrell commented
> failure_test: https://build.hpdd.intel.com/job/daos-stack/job/pipeline-lib/view/change-requests/job/PR-385/10/

This one reports the stage has no steps and has an error at the end of it:

```
[2023-07-06T15:04:23.221Z] java.lang.NullPointerException: Cannot invoke method startsWith() on null object
[2023-07-06T15:04:23.221Z] 	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
[2023-07-06T15:04:23.221Z] 	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:47)
[2023-07-06T15:04:23.221Z] 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
[2023-07-06T15:04:23.221Z] 	at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:34)
[2023-07-06T15:04:23.221Z] 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
[2023-07-06T15:04:23.221Z] 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
[2023-07-06T15:04:23.221Z] 	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:180)
[2023-07-06T15:04:23.221Z] 	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:182)
[2023-07-06T15:04:23.221Z] 	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:17)
[2023-07-06T15:04:23.221Z] 	at WorkflowScript.run(WorkflowScript:132)
```

But indeed, why would it report no steps?  I guess ultimately that `script` is not a reportable step if it doesn't produce any output?

> Success test with leap15 added: https://build.hpdd.intel.com/job/daos-stack/job/pipeline-lib/view/change-requests/job/PR-385/12/

Again a very silent test.  Which when it passes, I guess is OK.  But when it fails, we need to know what failed.

2023-07-07 17:06 UTC, brianjmurrell approved these changes

2023-07-07 17:35 UTC, merged